#title: Vladari cije ime sadrzi Stefan
#comment: Koristi FILTER sa CONTAINS za pretragu po imenu
PREFIX nemanjicischema: <http://iec.ch/TC57/NemanjiciSchema#>

SELECT ?ime ?titula ?od ?do
WHERE {
    ?v a nemanjicischema:Vladar ;
       nemanjicischema:Osoba.ime ?ime ;
       nemanjicischema:Vladar.titula ?titula ;
       nemanjicischema:Vladar.vladaoOd ?od ;
       nemanjicischema:Vladar.vladaoDo ?do .
    FILTER (CONTAINS(?ime, "Stefan"))
}
ORDER BY ?od
