#title: Wikidata - Bitke u kojima je ucestvovala Srbija
#comment: Endpoint: https://query.wikidata.org/
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?bitka ?ime ?datum
WHERE {
    ?bitka wdt:P31 wd:Q178561 ;
           rdfs:label ?ime .
    { ?bitka wdt:P710 ?ucesnik . ?ucesnik wdt:P17 wd:Q403 . }
    UNION
    { ?bitka wdt:P17 wd:Q403 }
    OPTIONAL { ?bitka wdt:P585 ?datum }
    FILTER (lang(?ime) = "en")
}
ORDER BY ?datum
LIMIT 20
