#title: Wikidata - Djeca Stefana Nemanje
#comment: Endpoint: https://query.wikidata.org/
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt:  <http://www.wikidata.org/prop/direct/>

SELECT DISTINCT ?ime ?rodjenje
WHERE {
    ?stefan rdfs:label "Stefan Nemanja"@en .
    ?dijete wdt:P22 ?stefan ;
            rdfs:label ?ime .
    FILTER(lang(?ime) = "en")
    OPTIONAL { ?dijete wdt:P569 ?rodjenje }
}
ORDER BY ?rodjenje
