#title: Wikidata - Djeca Stefana Nemanje
#comment: Endpoint: https://query.wikidata.org/
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>

SELECT ?dijete ?ime ?rodjenje
WHERE {
    SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
    ?stefan rdfs:label "Stefan Nemanja"@en .
    ?dijete wdt:P22 ?stefan ;
            rdfs:label ?ime .
    OPTIONAL { ?dijete wdt:P569 ?rodjenje }
    FILTER (lang(?ime) = "en")
}
