#title: DBpedia - Djeca Stefana Nemanje
#comment: Endpoint: https://dbpedia.org/sparql
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?dijete ?ime
WHERE {
    ?dijete dbo:parent dbr:Stefan_Nemanja ;
            rdfs:label ?ime .
    FILTER (lang(?ime) = "en")
}
