#title: Wikidata - Clanovi dinastije Nemanjica
#comment: Endpoint: https://query.wikidata.org/
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT DISTINCT ?osoba ?ime ?rodjenGodina
WHERE {
    ?dinastija rdfs:label ?dynLabel .
    FILTER(CONTAINS(LCASE(STR(?dynLabel)), "nemanj") && lang(?dynLabel) = "en")
    ?osoba wdt:P53 ?dinastija ;
           rdfs:label ?ime .
    OPTIONAL { ?osoba wdt:P569 ?r . BIND(YEAR(?r) AS ?rodjenGodina) }
    FILTER (lang(?ime) = "en")
}
ORDER BY ?rodjenGodina
