#title: Wikidata - Detalji o Svetom Savi
#comment: Endpoint: https://query.wikidata.org/
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>

SELECT ?propLabel ?valueLabel
WHERE {
    SERVICE wikibase:label { bd:serviceParam wikibase:language "en" . }
    wd:Q47624 wdt:P31 ?value .
    BIND("instanceOf" AS ?propLabel)
}
LIMIT 15
