PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?svojstvo ?vrijednost
WHERE {
    ?sveti rdfs:label "Saint Sava"@en .
    {
        BIND("mjesto rodjenja" AS ?svojstvo)
        ?sveti wdt:P19 ?v . ?v rdfs:label ?vrijednost .
        FILTER(lang(?vrijednost)="en")
    } UNION {
        BIND("otac" AS ?svojstvo)
        ?sveti wdt:P22 ?v . ?v rdfs:label ?vrijednost .
        FILTER(lang(?vrijednost)="en")
    } UNION {
        BIND("drzavljanstvo" AS ?svojstvo)
        ?sveti wdt:P27 ?v . ?v rdfs:label ?vrijednost .
        FILTER(lang(?vrijednost)="en")
    } UNION {
        BIND("zanimanje" AS ?svojstvo)
        ?sveti wdt:P106 ?v . ?v rdfs:label ?vrijednost .
        FILTER(lang(?vrijednost)="en")
    } UNION {
        BIND("datum rodjenja" AS ?svojstvo)
        ?sveti wdt:P569 ?vrijednost .
    } UNION {
        BIND("datum smrti" AS ?svojstvo)
        ?sveti wdt:P570 ?vrijednost .
    }
}