PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT DISTINCT ?ime
WHERE {
    ?bitka rdfs:label "Battle of Kosovo"@en .
    ?osoba wdt:P607 ?bitka ;
           wdt:P27 ?drzava ;
           rdfs:label ?ime .
    ?drzava rdfs:label ?drzavaNaziv .
    FILTER(CONTAINS(LCASE(STR(?drzavaNaziv)), "serbia") && lang(?drzavaNaziv) = "en")
    FILTER (lang(?ime) = "en")
}
ORDER BY ?ime